# Generated by Django 5.2.5 on 2025-08-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        # Add database indexes for optimal report performance
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_appointment_status_date ON api_appointment(status, scheduled_date);",
            reverse_sql="DROP INDEX IF EXISTS idx_appointment_status_date;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_appointment_professional_date ON api_appointment(professional_id, scheduled_date);",
            reverse_sql="DROP INDEX IF EXISTS idx_appointment_professional_date;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_appointment_service_date ON api_appointment(service_type_id, scheduled_date);",
            reverse_sql="DROP INDEX IF EXISTS idx_appointment_service_date;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_appointment_date_status ON api_appointment(scheduled_date, status);",
            reverse_sql="DROP INDEX IF EXISTS idx_appointment_date_status;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_appointment_completed_date ON api_appointment(scheduled_date) WHERE status = 'completed';",
            reverse_sql="DROP INDEX IF EXISTS idx_appointment_completed_date;"
        ),
    ]
